:figure-caption: Figure
:table-caption: Table
:sectnums:
:stem:
:last-update-label!:
:xrefstyle: short
:section-refsig:

:toc:
:toclevels: 4
:toc-title: Table of contents

= Basketball Rules

== Introduction

The purpose of this competition is to imitate a real basketball game.
There are 2 robots on the court, which try to get as many balls into the opponent's basket as possible.

== Court

=== General

General view of the basketball court is shown in <<image_court_angle>>.

[#image_court_angle]
.Competition area from an angle
image::images/competition_area_angled.svg[width=1000]

=== Dimensions

The competition area is divided into three different zones.

. Playing court is 4600 mm long and 3100 mm wide rectangular area.
Edge markings (white and black lines) are part of the playing court.
. Playing area includes playing court and extra zone for robots to move around.
Playing area is 6100 mm long and 4000 mm wide.
. Competitors area is an 950 – 1000 mm wide black carpet around the playing area.

[#court_surface]
=== Court surface

The surface of the playing area is orange needle felt carpet (ExpoRips 2007).
Surface beneath the carpet is hard and even.
Competitors area is covered with a black carpet.
Competition area is surrounded by white walls which are at least 450 mm high.

==== Court markings

Court markings are shown in <<image_court_markings>> and competition area dimensions in <<image_court_dimensions>>.

[#image_court_markings]
.Court markings
image::images/court_markings.svg[width=610]

[#image_court_dimensions]
.Competition area dimensions
image::images/competition_area_top_with_dimensions_en.svg[width=900]

Playing court is marked with white and black lines.
Lines (black and white) are part of the playing court.
All lines are 50 mm wide.
Playing court is divided into two halves with a white centerline.

== AR markers

There are two 160 x 160 mm ArUco markers on both backboards.
Markers are attached to the bottom corners of the backboard.
Markers can be seen in <<marker_basket_1_left>>, <<marker_basket_1_right>>, <<marker_basket_2_left>> and <<marker_basket_2_right>>.
Exact marker positions and dimensions can be found in <<image_basket_dimensions>>.

Markers are identified by marker's ID:

* *11* on the *left* of the *magenta* basket
* *12* on the *right* of the *magenta* basket
* *21* on the *left* of the *blue* basket
* *22* on the *right* of the *blue* basket

ArUco marker generator can be found here: http://chev.me/arucogen/.

[.float-group]
--
[#marker_basket_1_left]
.Marker 11
[.left]
image::images/marker_basket_1_left.svg[width=160]

[#marker_basket_1_right]
.Marker 12
[.left]
image::images/marker_basket_1_right.svg[width=160]

[#marker_basket_2_left]
.Marker 21
[.left]
image::images/marker_basket_2_left.svg[width=160]

[#marker_basket_2_right]
.Marker 22
[.left]
image::images/marker_basket_2_right.svg[width=160]
--

== Baskets

Baskets are placed in the middle of the endlines (shorter edges) on the playing court.
Backboard's side with the basket is in line with the black line's outer edge.
The colours of the baskets are matt blue (colour code: RAL5015) and matt magenta (colour code: RAL4010).
Playing court with baskets can be seen in <<image_court_angle>> and <<image_court_dimensions>>.

Basket is a painted pipe with following dimensions:

* height 500 mm
* outside diameter 160 mm
* inside diameter 148 mm

Attached to the basket is a white backboard with dimensions of 660 x 800 mm.
Basket dimension can be seen in <<image_basket_dimensions>>.

[#image_basket_dimensions]
.Basket in front view
image::images/basket_2_front_with_dimensions.svg[width=600]

[#balls]
== Balls

=== Dimensions and properties

Balls are green mini squash balls with a mass of around 24 grams and a diameter of around 40 mm.

=== Placement of the balls

Each round starts with 11 balls on the court.
The placement of the balls is random, but symmetrical for both robots with respect to the diagonal of the court.
At least 10 different ball placement combinations must be prepared for the games.
Ball placement will not change during a game.
During a game round, balls can be moved only by the competing robots of that game.

== Number of robots and team size

2 robots are on the court during the game, 1 per each team.
Up to 6 members can be registered to a team.

[#being_in_competition_area]
== Being in the competition area

=== Robots

. During a game, only robots competing in that game can be in the competition area.

=== All people

. During the games, everyone in the competition area must wear clothes which do not have the same colours that are present in the playing area or baskets (except for black).

=== Team members

. Only team members of the competing robots can be in the competition area during a game.
. During an active game, only one team member from each team is allowed in the playing area (outside playing court) for starting the robot.
Team member has to leave the competition area after starting the robot.
. When a game round is stopped, up to two team members from each team can be in the competition area.
. Entire team is allowed in the competition area between game rounds.
. Only teams of the game about to start are allowed in the competition area between the games.

=== Referees

. Referees can be in the competition area during the entire competition.
. Referees are not allowed in the playing area during an active round.

=== Organisers

. Organisers are only allowed to be in the competition area between games and game rounds.

=== Other people

. Only competitors, referees and organisers are allowed in the competition area.

[#robot_requirements]
== Requirements for the robot

[#robot_requirements_general]
=== General requirements
:xrefstyle: basic

Robot is a fully autonomous machine that carries its own energy source, movement mechanisms, management and control systems.
It is not allowed to use remote control to move the robot during a game.
Only one-way communication out of the robot and sending a start signal is allowed.

[#robot_requirements_mechanical]
=== Mechanical requirements for the robot

. Robot has to fit in an upright cylinder with a diameter of 350 mm and height of 350 mm the entire time during the game.
. Robot's mass must not exceed 8 kg.
. Majority of robot's external design must consist of black, white or gray colours.
It is not allowed to use ball and basket colours in the external design.
. The robot is not allowed to intentionally detach any parts during the game onto the court.

[#robot_requirements_electrical]
=== Electronic requirements for the robot
:xrefstyle: short

. The robot is not allowed to use LEDs during the game rounds (except by mutual agreement between the opposing teams).
Indicators and LEDs used in sensors are allowed if the LEDs do not violate the external design requirements (see <<robot_requirements_mechanical>>).
. If light spreading elements are used, their intensity must not be harmful to the human eye or they should be shielded from direct observation.
. If a laser is used, the emission of the laser (averaged over 1 second) must not be more than 1 mW/mm^2^.
. The robot must not intentionally deceive the optical sensors of the opponent robot (including the camera of the robot).
. Robot is allowed to be started manually.

=== Robot access to the competition
:xrefstyle: short

The robot, which does not comply with the requirements stated in sections <<robot_requirements_general>> - <<robot_requirements_electrical>>, is not allowed to participate in the competition.
Violating these requirements during the tournament will lead to removal from the competition.

[#robot_control_requirements]
=== Requirements for robot control

==== Definitions

. Ball out of play – ball that has at least once completely passed over the black line when viewed from the top.

==== General

The are no direct restrictions for operating a ball.
Basket is not counted when a ball that is out of play is thrown in the basket.

==== Robot penalisation and disqualification
:xrefstyle: basic

. Robot receives a foul when:
* the robot holds more than one ball at a time;
* the robot moves a basket:
* the robot damages the court or its parts, other robots, balls, referees, the opponent's team, spectators or other people surrounding the court.
Non-malicious pushing is allowed.
It is not allowed to damage the court and the opponent by the confused robot;
* the robot leaves the playing area (over half of the robot is out of the playing area, viewed from the top);
* robot's team member breaks the rules of being in the competition area (see <<being_in_competition_area>>);
* robot's team member moves the balls in the competition area during game's round.

. On first foul:
* the referee stops the game and the time;
* the robots must stop;
* the robot, which received the foul, *must be moved to the starting position* (see <<game_round>>);
* the opponent robot
** stays in the same place
** or is moved onto the black line at the place chosen by the team.
If the robot is holding a ball, then it must be left where it was at the time the foul was called;
* referee will resume the game and the game's time will continue from where it was stopped.

. On second foul:
* the referee stops the game and the time;
* the robots must stop;
* the robot, which received the foul, *must be removed from the playing area*;
* the opponent robot
** stays in the same place
** or is moved onto the black line at the place chosen by the team.
If the robot is holding a ball, then it must be left where it was at the time the foul was called;
* referee will resume the game and the game's time will continue from where it was stopped.

. Fouls are valid until the end of the round.

. The referee can stop the game and separate the robots from each other without issuing a foul.
In that case the time is stopped as well.

[#referee_signals]
=== Referee’s signals

Software has been created to manage the games and send the referee's signals.

Software and documentation is available from the following link:
https://github.com/ut-robotics/robot-basketball-manager

Reacting to referee's signals is not mandatory.
Software is still in development and referee's signals can change.

== Referees

Each game is coordinated by the head referee, who ensures the compliance of the competition and games to the competition rules.
The head referee is assisted by 2 basket referees.

=== Head referee
:xrefstyle: basic

The tasks of the head referee include:

* Carries out the technical inspection of the robots and decides which ones will be allowed to compete (see <<qualification>>).
* Ensures that the balls and their placement during the competitions complies with the competition rules (see <<balls>>).
* Starts, stops, and ends the game.
* Informs the players and assistant referees about the beginning and end of the round (see <<game_round>>).
* Gives the order to the team to remove robot from the game until the end of the round if any of the requirements given in <<robot_control_requirements>> are violated.
* Ends the game round if both robots have violated the requirements given in <<robot_control_requirements>>.
* If necessary, can stop or end the game if there appears to be any external disruptive factors.
* May remove misbehaving team members from the competition area.
* Ensures that the spectators do not enter the competition area (see <<being_in_competition_area>>).

The head referee's decisions related to the game and rounds are final.
The head referee has the right to change his or her decision if any relevant additional information occurs.

== Competition arrangement

There are two different tournament systems used.
Competition starts with Swiss-system tournament to determine 4 best robots.
By Swiss-system tournament rules, in the first round of games, the robots are matched randomly.
Other rounds of games will match the robots with the closest standings.
If there are odd number of competitors, then one of the robots in each round of games gets a bye, which means automatic victory.
None of the robots will compete against each other twice and no robot gets two byes. 

Minimum number of Swiss-system tournament rounds is asciimath:[ceil(log_2 n_(rob\ot))]:

* 1 - 4 robots do not need to play any Swiss-system games.
* 5 - 8 robots will play 3 rounds.
* 9 - 16 robots will play 4 rounds.
* 17 - 32 robots will play 5 rounds.

After that there will be a double-elimination tournament between the 4 best robots.
This will reveal the final ranking.

== Game arrangement

One game consists of 3 or 2 (if both rounds are won by one robot) main rounds and if necessary then also 3 extra rounds and free throw rounds.
The game is won by having more main round wins.
If the main rounds end with a draw, then the robot that is the first to win an extra round, wins the game.
If extra rounds end with a draw, then the winner will be determined with free throws.
Swiss-system games can end with a draw and no extra rounds or free throws will be played.

Robots have to change sides after every round.
Sides must be changed in 2 minutes.

[#game_round]
== Round arrangement

One main round lasts for 60 seconds.
Extra round lasts for 30 seconds.
In the beginning of each round, both robots are positioned in the right corner (viewed from the back of the basket) of their side of the court.
The robots must touch the point where the black endline and black sideline meet.
The round begins and ends with head referee's signal.
At the end of the round, both robots must stop.
If a foul is made then the time will be stopped.

== Scoring

Each ball that is fully in the basket gives one point.
The balls that are out of play are not counted.
Round is won by having more points.

== Free throw arrangement
:xrefstyle: short

At least 3 free throw rounds must be played.
Both robots must perform one free throw in each round.
Only one basket is used and it will be chosen by the referee.
Only 1 ball is on the court and it is placed 1300 mm away from the basket on the same line with both of the baskets (see <<image_court_dimensions>>).
The winner of free throw rounds is the robot which has scored more baskets.
If first three rounds end with a draw then additional rounds will be played until a round is won by a robot.

Free throw procedure:

. Robot starts the free throw from the center of the court.
. Robot has 10 seconds to throw.
. Free throw starts with referee's signal.
. Free throw ends if the throw has been made or the referee has stopped the round.

[#qualification]
== Technical inspection
:xrefstyle: basic

Technical inspection is carried out in the morning of the competition day.
During the technical inspection, the head referee inspects if the robot meets the requirements (see <<robot_requirements>>) and tests the capability to compete.
In order to show the capability to compete, the robot has to score at least 1 ball out of 5 balls in 60 seconds, while being alone in the court.
Non-compliant robots and robots incapable to compete are not allowed to participate in the competition.

== Organisation

. The robot must be registered before the competition.
The registration process includes technical inspection of the robot.
. Technical inspection must be completed by the time that is specified by the organisers.
. All questions and problems arising during the competition are solved by the referee.
. All complaints must be reported before the start of the next game.
. The final decision regarding any disputes or inconsistencies is always made by the referee or the organisers.
